### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by pstewart726** [gigablast/open-source-search-engine#108]
Hi folks..

looking for feedback on if this project is dead or not?  I've tried numerous times to reach Matt Wells, whom in the past was very helpful and responsive.  Almost all email addresses on the Gigablast website bounce back .... didn't know where else to ask so thought I'd try here.

Thanks!
Paul

**Comment by isj-privacore** [comment]
There are other more active forks, eg https://github.com/privacore/open-source-search-engine. But don't expect them to be a drop-in replacement.
Also, Matt might be working on his Pro edition instead of the open-source one.

**Comment by pstewart726** [comment]
Wow... that's really interesting re: privacore! Thanks for that note.. I tried to reach Matt as I had the privilege of discussing ideas and asking questions previously but it seems that he has been busy (and changed all his email addresses).  Is there a way to migrate from Gigablast to Privacore cleanly (the data sets)?

**Comment by isj-privacore** [comment]
Yes, there is a way to cleanly migrate, but that is best discussed on that fork.

**Comment by gigablast** [comment]
it's not dead yet! i am indeed putting most work into pro, but am planning some significant updates soon. what is it you are looking for exactly?

**Comment by pstewart726** [comment]
Thank you - I had tried emailing all of the email addresses I could find on your website to discuss Pro and partnership opportunities ... glad to hear you're alive and kicking! :)

**Comment by turbo** [comment]
significant update hype!

**Comment by lisawebcoder** [comment]
hello i too cant reach any email address that i send to
anyway regrading the API is it set in the code so that it can only work on the host IP machine
because the API calls work for me when i am in my place but if i go to like any other location and connect to the Net and i try the API it doesnt work just gives  JSON parse error

and for that matter if i just use "&format=json" and you go to the endpoint it gives an unprettyifgied JSON return but the thing is in my webapp it still returns an error JSON parse eror 1st < becaue its returning HTML
why??
Lisa
good day

also i am trying to just run the software from build from source and i run it ok in my localhost but i cant get it to run in the cloud linux server

do we need to change the IP address in the host.conf file in the html folder?
i cant find any guide int he docs on how to deploy in the cloud live in the Net

does anyone know?

Lisa
