### ISSUE TITLE
Folder linking and binary issue

### ISSUE THREAD

**Issue by UltraNote** [gigablast/open-source-search-engine#154]
Getting lot of errors posted to shell terminal due to missing folders or binaries 

Anyone can help?

![3C972476-507B-4BA7-A59D-788D1551CEE7](https://user-images.githubusercontent.com/31513990/67775050-ab573600-fa5e-11e9-81ac-081038212d82.jpeg)

**Comment by lisawebcoder** [comment]
hello i am getting this error as i still try to get the search machine project running
also do you know hpow to connect to the APIs?
i easliy connect to wikipedia APIs but hee i dont 
but anyway i much rather built from scratch the source code here is the rrors i am at

lisa

the make command gets to the final stage where it seems all built but there is still eroors
that i dont know the fix
i had to fix a small throw line error in Mem.cpp then i found the fix was small
but this one i dont understand or can find so far an online fix

Lisa

g++ -D_REENTRANT_ -D_CHECK_FORMAT_STRING_ -I. -g -Wall -pipe -fno-stack-protector -Wno-write-strings -Wstrict-aliasing=0 -Wno-uninitialized -DPTHREADS -Wno-unused-but-set-variable -o gb main.o UdpSlot.o Rebalance.o Msg13.o Mime.o PageGet.o PageHosts.o PageParser.o PageInject.o PagePerf.o PageReindex.o PageResults.o PageAddUrl.o PageRoot.o PageSockets.o PageStats.o PageTitledb.o PageAddColl.o hash.o Domains.o Collectiondb.o linkspam.o ip.o sort.o fctypes.o XmlNode.o XmlDoc.o Xml.o Words.o Url.o UdpServer.o Threads.o Titledb.o HashTable.o TcpServer.o Summary.o Spider.o Catdb.o RdbTree.o RdbScan.o RdbMerge.o RdbMap.o RdbMem.o RdbBuckets.o RdbList.o RdbDump.o RdbCache.o Rdb.o RdbBase.o Query.o Phrases.o Multicast.o Msg9b.o Msg8b.o Msg5.o Msg39.o Msg3.o Msg22.o Msg20.o Msg2.o Msg1.o Msg0.o Mem.o Matches.o Loop.o Log.o Lang.o Indexdb.o Posdb.o Clusterdb.o IndexList.o Revdb.o HttpServer.o HttpRequest.o HttpMime.o Hostdb.o Highlight.o File.o Errno.o Entities.o Dns.o Dir.o Conf.o Bits.o Stats.o BigFile.o Msg17.o Speller.o PingServer.o StopWords.o TopTree.o Parms.o Pages.o Unicode.o iana_charset.o Iso8859.o SearchInput.o Categories.o Msg2a.o PageCatdb.o PageDirectory.o SafeBuf.o Datedb.o UCNormalizer.o UCPropTable.o UnicodeProperties.o Pops.o Title.o Pos.o LangList.o Profiler.o AutoBan.o Msg3a.o HashTableT.o HashTableX.o PageLogView.o Msg1f.o Blaster.o MsgC.o PageSpam.o Proxy.o PageThreads.o Linkdb.o matches2.o LanguageIdentifier.o Language.o Repair.o Process.o Abbreviations.o RequestTable.o TuringTest.o Msg51.o geo_ip_table.o Msg40.o Msg4.o SpiderProxy.o LanguagePages.o Statsdb.o PageStatsdb.o PostQueryRerank.o Msge0.o Msge1.o CountryCode.o DailyMerge.o CatRec.o Tagdb.o Users.o Images.o Wiki.o Wiktionary.o Scraper.o Dates.o Sections.o SiteGetter.o Syncdb.o qa.o Placedb.o Address.o Test.o GeoIP.o GeoIPCity.o Synonyms.o Cachedb.o Monitordb.o dlstubs.o PageCrawlBot.o Json.o PageBasic.o Punycode.o Version.o -lm -lpthread -lssl -lcrypto ./libiconv64.a ./libz64.a
/usr/bin/ld: ./libiconv64.a(iconv.o): relocation R_X86_64_32S against .rodata' can not be used when making a PIE object; recompile with -fPIC /usr/bin/ld: ./libiconv64.a(localcharset.o): relocation R_X86_64_32 against .rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libz64.a(deflate.o): relocation R_X86_64_32S against hidden symbol zcalloc' can not be used when making a PIE object /usr/bin/ld: ./libz64.a(inflate.o): relocation R_X86_64_32S against hidden symbol zcalloc' can not be used when making a PIE object
/usr/bin/ld: ./libz64.a(inftrees.o): relocation R_X86_64_32S against .rodata' can not be used when making a PIE object; recompile with -fPIC /usr/bin/ld: ./libz64.a(trees.o): relocation R_X86_64_32S against .data' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libz64.a(zutil.o): relocation R_X86_64_32 against .rodata' can not be used when making a PIE object; recompile with -fPIC /usr/bin/ld: ./libz64.a(crc32.o): relocation R_X86_64_32 against .rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libz64.a(inffast.o): relocation R_X86_64_32S against .rodata' can not be used when making a PIE object; recompile with -fPIC TcpServer.o: In function TcpServer::reset()':
/home/robert/Desktop/gigablast/open-source-search-engine-master/TcpServer.cpp:61: undefined reference to ERR_free_strings' TcpServer.o: In function TcpServer::init(void ()(TcpSocket), int ()(char, int, TcpSocket*), int ()(TcpSocket), short, int*, bool)':
/home/robert/Desktop/gigablast/open-source-search-engine-master/TcpServer.cpp:206: undefined reference to SSL_library_init' /home/robert/Desktop/gigablast/open-source-search-engine-master/TcpServer.cpp:207: undefined reference to SSL_load_error_strings'
/home/robert/Desktop/gigablast/open-source-search-engine-master/TcpServer.cpp:211: undefined reference to `SSLv23_method'
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:196: recipe for target 'gb' failed
make: *** [gb] Error 1
